name: "Async: CSV to JSON"

on:
  push

jobs:
  task_1:
    runs-on: ubuntu-latest
    steps:
    - name: "Установка зависимостей"
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: 2.0.8
    - uses: actions/checkout@v4
    - name: "Сборка main"
      run: nim c main
    - name: "Запуск main"
      run: ./main